fix mongodb replicaset and host name by init-mongo job

diff --git a/templates/mongo.yaml b/templates/mongo.yaml
--- a/templates/mongo.yaml
+++ b/templates/mongo.yaml
@@ -25,18 +25,6 @@ spec:
         - name: {{ .Values.essentials.mongo.name | default "mongo"}}
           {{- if $replicaset }}
           image: "harborreg-2.northeurope.cloudapp.azure.com/library/mongo:replicaSet"
-          lifecycle:
-            postStart:
-              exec:
-                command: 
-                  - "sh"
-                  - "-c"
-                  - >
-                    while [ "$(grep -v "rem_address" /proc/net/tcp | grep 6989)" = "" ];
-                    do
-                      echo "wating for monog to listen on port 27017"
-                    done;
-                    mongo --eval 'rs.initiate({_id: "rs0", members: [{_id: 0, host: "localhost:27017"}]})';
           {{- else }}
           image: {{ .Values.essentials.mongo.image | default "mongo"}}
           {{- end }}
@@ -56,4 +44,67 @@ spec:
       name: mongo
       port: {{ .Values.essentials.mongo.port | default 27017 }}
       targetPort: {{ .Values.essentials.mongo.port | default 27017}}
+
+---
+{{- if $replicaset }}
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: init-mongo-replicaset
+data:
+  init-mongo-replicaset.sh: |
+    #!/bin/sh    
+    ATTEMPTS=0 ; LIMIT=59 ;
+
+    mongo --host localhost --eval 'rs.initiate({_id: "rs0", members: [{_id: 0, host:"localhost:27017"}]})';
+  
+    STATUS=$?
+    
+    echo  $STATUS
+    
+    until [ $STATUS = 0 ]
+    do
+      ATTEMPTS=`expr $ATTEMPTS + 1` ;
+      echo \"Failed attempts: $ATTEMPTS\" ;
+      if [ $ATTEMPTS -gt $LIMIT ]; then
+        exit 1 ;
+      fi ;
+      sleep 2 ; # 1 second intervals between attempts
+      
+      mongo --host mongo --eval 'rs.initiate({_id: "rs0", members: [{_id: 0, host:"mongo:27017"}]})';
+
+      STATUS=$? ;
+    
+    done ;
+    set -e ; # reset `e` as active
+---
+
+apiVersion: batch/v1
+kind: Job
+metadata:
+  name: "mongo-init"
+  labels:
+    {{- include "master-chart.labels" . | nindent 4 }}
+    app: {{ default "mongo-init"}}
+spec:
+  backoffLimit: 2
+  template:
+    metadata:
+      labels:
+        app: {{ default "mongo-init"}}
+    spec:
+      containers:
+        - name: "mongo-init"
+          image: "harborreg-2.northeurope.cloudapp.azure.com/library/mongo:replicaSet"
+          command: ["/bin/sh" , "/init/init-mongo-replicaset.sh"]
+          volumeMounts:
+            - name: init-mongo-replicaset
+              mountPath: "/init"
+      volumes:
+        - name: init-mongo-replicaset
+          configMap:
+            name: init-mongo-replicaset
+            defaultMode: 0745
+      restartPolicy: OnFailure
+{{- end }}
 {{- end -}}
